name: Build & Publish Debug/Release APK

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Use github keystore for release
        run: |
          echo 'RELEASE_STORE_FILE=github.keystore' >> gradle.properties
          echo 'RELEASE_STORE_PASSWORD=123456789' >> gradle.properties
          echo 'RELEASE_KEY_ALIAS=key' >> gradle.properties
          echo 'RELEASE_KEY_PASSWORD=123456789' >> gradle.properties

      - name: Build Debug APK
        if: github.ref_type == 'branch'
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: github.ref_type == 'tag'
        run: ./gradlew assembleRelease

      - name: Set APK path
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "APK_PATH=app/build/outputs/apk/release/app-release.apk" >> $GITHUB_ENV
            echo "APK_NAME=app-release.apk" >> $GITHUB_ENV
          else
            echo "APK_PATH=app/build/outputs/apk/debug/app-debug.apk" >> $GITHUB_ENV
            echo "APK_NAME=app-debug.apk" >> $GITHUB_ENV
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_PATH }}

      - name: Publish APK
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2.6.1
        with:
          files: ${{ env.APK_PATH }}